##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: http://mbmgweb1c.mtech.edu
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: Information/Collections/M-K-Jones
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Marion K Jones Collection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Maps, Reports, and history of M.K. Jones' work
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Marion Kay “M.K.” Jones, graduated from the University of Wyoming in 1956 with a degree in Petroleum Geology. He
worked for the Carter Oil Company in the Miles City, Montana office before a 3 ½ year stint as an aviator and Lieutenant
in the U.S. Army. In 1960 he joined Humble Oil as a staff geologist in Billings, Montana, eventually striking out on his
own as a Consulting Geologist. He formed a company called Discovery Energy and established a respected reputation as
a wellsite geologist and prospect generator across Montana and North Dakota. Kay served as a past president of the
Billings Geological Society (later the Montana Geological Society) and wrote several papers for the Society and gave
numerous conference presentations throughout his career. His understanding of complex geologic correlations ranging
from the Sweet Grass Arch of Montana to the east flank Mississippian shorelines and subcrops of the Williston Basin in
North Dakota was unrivaled by his peers."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: Jones; oil; gas; Marion Kay; M.K.; petroleum; geology
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: MBMG Data Preservation

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: mkjones_metadata
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Montana Bureau of Mines and Geology"
organization-link: https://www.mbmg.mtech.edu
organization-logo-banner: assets\img\MBMG2012LogoTransparent.png
organization-logo-nav: assets\img\logombmg.png

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
